GET http://localhost:3000/todos/?priority=LOW&status=TO%20DO

###

GET http://localhost:3000/todos/1

###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 1,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###

PUT http://localhost:3000/todos/1
Content-Type: application/json

{ "status": "DONE" }

###

DELETE http://localhost:3000/todos/1

###